project:
  type: website

website:
  title: "Ben Dahmen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maintenance.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

