---
title: "CV"
format:
  html:
    toc: true
  pdf:
    author: Ben Dahmen
    pdf-engine: weasyprint
css: css/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
bendahmen.github.io
b.a.dahmen\@lse.ac.uk
:::

## EDUCATION

**PhD -- Economics** <br> *London School of Economics* [*Sep 2022 --- Present*]{.cvdate}

::: print-only
-   Research Interests: Labor Economics, Public Economics
:::

-   Supervisors:
    -   Steve Pischke
    -   Alan Manning
    -   Johannes Spinnewijn

**MSc -- Economics** <br> *London School of Economics* [*Sep 2020 --- Jul 2021*]{.cvdate}

**BSc -- Economics & Business Economics** <br> *Erasmus University Rotterdam* [*Sep 2016 --- Jul 2019*]{.cvdate}

## WORK EXPERIENCE

**Predoctoral Research Assistant Public Economics** <br> *London School of Economics* [*July 2021 -- June 2022*]{.cvdate}

**Research Assistant in the Education, Labor and Pensions Sector** <br> *CPB Netherlands Bureau for Economic Policy Analysis* [*Sep 2019 -- Mar 2020*]{.cvdate}

## TEACHING

**London School of Economics** <br> *EC1A3 - Microeconomics I* [*2023/24*]{.cvdate} <br> *EC2B3 - Macroeconomics II* [*2023/24 -- 2026/26*]{.cvdate} <br> *PP410 - Public Economics for Public Policy* [*2024/25 -- 2025/26*]{.cvdate}

### Awards

**London School of Economics** <br> *Excellence in Education Award* [*2024/25*]{.cvdate} <br> *LSE Class Teacher Award (Highly Commended)* [*2024/25*]{.cvdate} <br> *LSE Teaching Bonus Award* [*2023/24*]{.cvdate}
